# Generated by Django 2.2.3 on 2019-07-16 03:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='name',
            field=models.CharField(default='My Quiz', max_length=50),
        ),
        migrations.AddField(
            model_name='quiz',
            name='taken_by',
            field=models.ManyToManyField(related_name='taken_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='authored_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
